---
# follows the same parameter structure as the DB extractor configuration
cognite: # kwargs to pass to the CogniteClient, Environment variable format: ${ENVIRONMENT_VARIABLE}
  # host: https://${EXTPIPES_CDF_CLUSTER}.cognitedata.com/
    host: ${EXTPIPES_CDF_HOST}
    project: ${EXTPIPES_CDF_PROJECT}
  #
  # AAD IdP login credentials:
  #
    idp-authentication:
        client-id: ${EXTPIPES_IDP_CLIENT_ID}
        secret: ${EXTPIPES_IDP_CLIENT_SECRET}
        scopes:
            - ${EXTPIPES_IDP_SCOPES}
        token_url: ${EXTPIPES_IDP_TOKEN_URL}

logger:
    file:
        path: ./logs/extpipes-deploy.log
        level: INFO
    console:
        level: INFO

# extpipe-pattern only documentation atm
extpipe-pattern: '{source}:{short-name}:{rawtable-name}:{suffix}'

# can contain multiple contacts, can be overwritten on pipeline level
default-contacts:
    - name: Joergen Wessel
      email: joergen.wessel@cognite.com
      role: SA
      send-notification: true

rawdbs:
  - rawdb-name: src:001:sap:db
    dataset-external-id: src:001:sap:ds
    short-name: sap
    rawtables:
      - rawtable-name: raw_assets
        pipelines:
        - source: csv
          schedule: On trigger
  - rawdb-name: src:003:opcua:db
    dataset-external-id: src:003:opcua:ds
    short-name: oee
    rawtables:
      - rawtable-name: raw_timeseries
        pipelines:
        - source: csv
          schedule: On trigger          
  - rawdb-name: src:003:opcua:db
    dataset-external-id: src:003:opcua:ds
    short-name: oee
    rawtables:
      - rawtable-name: datapoints
        pipelines:
        - source: rest-api
          schedule: On trigger